name: vilasesmo
description: Projeto VilaSesmo para controle do mercadinho interno.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.13.1'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  animated_bottom_navigation_bar: ^1.2.0  
  material_design_icons_flutter: ^6.0.7096
  carousel_slider: ^4.2.1
  dots_indicator: ^2.1.1
  dio: ^4.0.6
  dartz: ^0.10.1
  shared_preferences: ^2.1.1
  font_awesome_flutter: ^10.4.0
  flare_flutter: ^3.0.2
  animated_snack_bar: ^0.3.1
  badges: ^2.0.3
  image_picker: ^0.8.7+5
  image_cropper: ^4.0.1
  string_validator: ^1.0.0
  infinite_scroll_pagination: ^3.2.0
  curved_progress_bar: ^1.0.2
  cached_network_image: ^3.2.3
  timeago: ^3.5.0
  flutter_slidable: ^3.0.0
  qr_code_scanner: ^1.0.1
  barcode: ^2.2.4
  flutter_svg: ^2.0.7
  flutter_typeahead: ^5.0.1
  window_manager: ^0.2.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.2.0
  modular_test: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
  - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/appicon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/appicon.png"
    icon_size: 100 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/appicon.png"