version: '3'

services:

  seq:
      image: datalust/seq:latest
      ports:
          - 5341:80
      environment:
          ACCEPT_EULA: "Y"

  postgres:
    image: postgres:15.2
    volumes:
      - ${DATABASE_DATA_DIR}:/var/lib/postgresql/data
      - ${DATABASE_LOG_DIR}:/var/log/postgresql
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata

  pgadmin:
    image: 'dpage/pgadmin4:7.0'    
    volumes:
      - '${PGADMIN_DATA}:/var/lib/pgadmin'
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - '${PGADMIN_PORT}:80'
    depends_on:
      - postgres