services:

  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.14
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ${ZOOKEEPER_DATA_DIR}:/var/lib/zookeeper/data
      - ${ZOOKEEPER_LOG_DIR}:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    ports:
      - ${KAFKA_PORT}:9092
    user: root
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    restart: always
    volumes:
      - ${KAFKA_DATA_DIR}:/var/lib/kafka/data
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop:4.0.0
    ports:
      - ${KAFKA_DROP_PORT}:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
    depends_on:
      - kafka

  seq:
    image: datalust/seq:2023.3
    restart: unless-stopped
    ports:
      - ${SERILOG_PORT}:80
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - ${SERILOG_DATA_DIR}:/data

  postgres:
    image: postgres:15.2
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ${DATABASE_DATA_DIR}:/var/lib/postgresql/data
      - ${DATABASE_LOG_DIR}:/var/log/postgresql

  pgadmin:
    image: dpage/pgadmin4:7.0
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    volumes:
      - ${PGADMIN_DATA}:/var/lib/pgadmin
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - postgres

  mongo:
    image: mongo:5
    volumes:
      - ${MONGODB_DATA}:/data/db
    ports:
      - ${MONGODB_PORT}:27017

  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - ${MONGOEXPRESS_PORT}:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    depends_on:
      - mongo

  gateway:
    image: nginx
    restart: always
    volumes:
      - ${NGINX_CONF}:/etc/nginx/nginx.conf:ro
    ports:
      - ${NGINX_PORT}:80
