version: "3.4"

services:
  mongobackup:
    image: mongo:5
    volumes:
      - ${MONGODB_BACKUP_PATH}:/backup
    environment:
      MONGODB_BACKUP_URL: ${MONGODB_BACKUP_URL}
    command: >
      sh -c "mongodump --uri=\"$$MONGODB_BACKUP_URL\" --out=\"/backup/$$(date +%Y-%m-%d_%H-%M-%S)\""

  mongorestore:
    image: mongo:5
    volumes:
      - ${MONGODB_RESTORE_PATH}:/backup
    environment:
      MONGODB_RESTORE_URL: ${MONGODB_RESTORE_URL}
      MONGODB_RESTORE_DB: ${MONGODB_RESTORE_DB}
    command: >
      sh -c "mongorestore --uri=\"$$MONGODB_RESTORE_URL\" --db=\"$$MONGODB_RESTORE_DB\" /backup/$$MONGODB_RESTORE_DB"

  pgbackup:
    image: postgres:15.2          
    volumes:
      - ${POSTGRES_BACKUP_PATH}:/backup    
    environment:
      POSTGRES_HOST: ${POSTGRES_BACKUP_HOST}
      POSTGRES_PORT: ${POSTGRES_BACKUP_PORT}
      POSTGRES_USER: ${POSTGRES_BACKUP_USER}
      POSTGRES_PASSWORD: ${POSTGRES_BACKUP_PASSWORD}
      POSTGRES_BACKUP_DB_1: ${POSTGRES_BACKUP_DB_1}
      POSTGRES_BACKUP_DB_2: ${POSTGRES_BACKUP_DB_2}
      POSTGRES_BACKUP_DB_3: ${POSTGRES_BACKUP_DB_3}
    entrypoint: >
        sh -c "export PGPASSWORD=${POSTGRES_BACKUP_PASSWORD} &&
               pg_dump -U \"$$POSTGRES_USER\" -h \"$$POSTGRES_HOST\" -p \"$$POSTGRES_PORT\" -d $${POSTGRES_BACKUP_DB_1} > \"/backup/backup_$${POSTGRES_BACKUP_DB_1}_$$(date +%Y-%m-%d_%H-%M-%S).sql\" &&
               pg_dump -U \"$$POSTGRES_USER\" -h \"$$POSTGRES_HOST\" -p \"$$POSTGRES_PORT\" -d $${POSTGRES_BACKUP_DB_2} > \"/backup/backup_$${POSTGRES_BACKUP_DB_2}_$$(date +%Y-%m-%d_%H-%M-%S).sql\" &&
               pg_dump -U \"$$POSTGRES_USER\" -h \"$$POSTGRES_HOST\" -p \"$$POSTGRES_PORT\" -d $${POSTGRES_BACKUP_DB_3} > \"/backup/backup_$${POSTGRES_BACKUP_DB_3}_$$(date +%Y-%m-%d_%H-%M-%S).sql\""

  pgrestore:
    image: postgres:15.2
    volumes:
      - ${POSTGRES_RESTORE_PATH}:/backup
    environment:
      POSTGRES_HOST: ${POSTGRES_RESTORE_HOST}
      POSTGRES_PORT: ${POSTGRES_RESTORE_PORT}
      POSTGRES_USER: ${POSTGRES_RESTORE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_RESTORE_PASSWORD}
    entrypoint: >
      sh -c "export PGPASSWORD=$$POSTGRES_PASSWORD &&\
      restore_file=\"/backup/${POSTGRES_FILE_BACKUP_DB_1}\" &&\
      psql -U \"$$POSTGRES_USER\" -h \"$$POSTGRES_HOST\" -p \"$$POSTGRES_PORT\" -d ${POSTGRES_RESTORE_DB_1} \"$$restore_file\" &&\
      restore_file=\"/backup/${POSTGRES_FILE_BACKUP_DB_2}\" &&\
      psql -U \"$$POSTGRES_USER\" -h \"$$POSTGRES_HOST\" -p \"$$POSTGRES_PORT\" -d ${POSTGRES_RESTORE_DB_2} \"$$restore_file\" &&\
      restore_file=\"/backup/${POSTGRES_FILE_BACKUP_DB_3}\" &&\
      psql -U \"$$POSTGRES_USER\" -h \"$$POSTGRES_HOST\" -p \"$$POSTGRES_PORT\" -d ${POSTGRES_RESTORE_DB_3} \"$$restore_file\""
